spring:
  application:
    name: ${APP_NAME:BloodPressureTracker}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
    url: ${APP_DATASOURCE_URL}
    hikari:
      schema: ${APP_DATASOURCE_SCHEMA}
    flyway:
      enabled: true
      validate-on-migrate: true
  jpa:
    show-sql: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: ${APP_KAFKA_CONSUMER_BOOTSTRAP_SERVERS:localhost:29092}
      group-id: ${APP_KAFKA_GROUP_ID:bp-statistics-consumers}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.stacykarab.bloodpressuretracker
    producer:
      acks: -1
      bootstrap-servers: ${APP_KAFKA_PRODUCER_BOOTSTRAP_SERVERS:localhost:29092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
